# docker-compose.yml
version: '3.8' # Specify the Docker Compose file format version

services:
  # MinIO Object Storage Service (ONLY include this service)
  minio:
    image: quay.io/minio/minio:latest # Use the latest MinIO image
    container_name: minio-server # Name for the container
    ports:
      - "9000:9000" # MinIO API port (your Spring Boot app connects here)
      - "9001:9001" # MinIO Console port (for your browser UI)
    environment:
      MINIO_ROOT_USER: minioadmin # MinIO Access Key
      MINIO_ROOT_PASSWORD: minioadmin # MinIO Secret Key
    command: server /data --console-address ":9001" # Command to run MinIO server
    volumes:
      - minio_data:/data # Persistent volume for MinIO data
    healthcheck: # Optional: Health check to ensure MinIO is ready
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

# Define named volume for MinIO's persistent data
volumes:
  minio_data: